### ISSUE TITLE
Current travis config leads to (up to) 4 coverage reports on coveralls per file

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#144]
This is due to the fact that the travis config defines 4 python versions to run on.
https://github.com/d-Rickyy-b/pastepwn/blob/f9bd202d0813aebb6bc3f189a43158227ca2bdea/.travis.yml#L3-L7

![grafik](https://user-images.githubusercontent.com/5798157/66507984-83645a80-ead0-11e9-93e7-6820f44a421e.png)

This could be fixed with to a [build matrix](https://docs.travis-ci.com/user/build-matrix/#using-different-programming-languages-per-job) which is adding the after_success command only on one python version.

https://github.com/d-Rickyy-b/pastepwn/blob/f9bd202d0813aebb6bc3f189a43158227ca2bdea/.travis.yml#L18-L19

**Comment by wescran** [comment]
I'm new to travis-ci but can take a shot at this :)

**Comment by wescran** [comment]
Hi, just a quick question. Out of the 4 python versions in `.travis.yml` which one would you like to have for the after_success command?

**Comment by d-Rickyy-b** [comment]
@wescran Hi there. Fair question! I would like to always use the newest python version (which is specified in the config) - in this case 3.7.

**Comment by wescran** [comment]
Okay so I started out with writing a build matrix for using `3.7` but then I found there was a [travis environment variable](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables) for the python version used in the job. So I wondered if it would be easier to just have a conditional for the `after_success` phase using the `TRAVIS_PYTHON_VERSION`. 

This is what I had for the build matrix:
```
language: python
sudo: require
python:
  - "3.4"
  - "3.5"
  - "3.6"
# matrix to create one coverage report on coveralls
matrix:
  include:
    - python: "3.7"
      # command to install dependencies
      install:
        - pip install -r requirements.txt
        - pip install python-coveralls
      # command to run tests
      script:
        - python -m compileall ./
        - coverage run --omit='*/virtualenv/*,*/site-packages/*' -m unittest discover -s . -v -p "*_test.py"
      after_success:
        - coveralls

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls

# command to run tests
script:
  - python -m compileall ./
  - coverage run --omit='*/virtualenv/*,*/site-packages/*' -m unittest discover -s . -v -p "*_test.py"
```

but I am wondering if this might be a better option:

```
language: python
sudo: require
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls

# command to run tests
script:
  - python -m compileall ./
  - coverage run --omit='*/virtualenv/*,*/site-packages/*' -m unittest discover -s . -v -p "*_test.py"

after_success:
  - test $TRAVIS_PYTHON_VERSION == '3.7' && coveralls
```

I went and tested these different configs which both worked. If these are correct, which one would you prefer?
